### ISSUE TITLE
Prop `id` did not match. Server: "react-select-5-input" Client: "react-select-3-input"

### ISSUE THREAD

**Issue by adrienclay36** [Tintef/react-google-places-autocomplete#288]
I'm not sure what's causing this. I am able to put GooglePlacesAutocomplete in a Modal (using Mantine) without issue, however if I try to render it directly to the page I get the following:

```
next-dev.js?3515:24 Warning: Prop `id` did not match. Server: "react-select-5-input" Client: "react-select-3-input"
    at input
    at div
    at n (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:40:9736)
    at div
    at eval (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:35:11730)
    at Input (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:40:43332)
    at div
    at eval (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:35:11730)
    at ValueContainer (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:40:45131)
    at div
    at eval (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:35:11730)
    at Control (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:40:41937)
    at div
    at eval (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:35:11730)
    at SelectContainer (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:40:44695)
    at o (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:40:70978)
    at o (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:40:97772)
    at r (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:40:95096)
    at eval (webpack-internal:///./node_modules/react-google-places-autocomplete/build/index.es.js:40:104058)
    at div
    at section
```
Here is the code snippet:

```
import React from "react";
import GooglePlacesAutocomplete from "react-google-places-autocomplete";
const BrowseSection = () => {
  return (
    <section className="container">
      <div className="w-11/12 lg:w-2/6 md:w-3/6 mx-auto mb-12">
        <GooglePlacesAutocomplete apiKey={process.env.NEXT_PUBLIC_GOOGLE_API}/>
      </div>
    </section>
  );
};

export default BrowseSection;
```

**Comment by Tintef** [comment]
This is a react-select usage issue, not of this component. According [this issue](https://github.com/JedWatson/react-select/issues/2629#issuecomment-473037019) I found in a lazy google search you should pass down an `id` and an `instanceId` to the underlying react-select

```
import React from "react";
import GooglePlacesAutocomplete from "react-google-places-autocomplete";
const BrowseSection = () => {
  return (
    <section className="container">
      <div className="w-11/12 lg:w-2/6 md:w-3/6 mx-auto mb-12">
        <GooglePlacesAutocomplete
          apiKey={process.env.NEXT_PUBLIC_GOOGLE_API}
          selectProps={{ id: <your-id>, instanceId: <your-id> }}
        />
      </div>
    </section>
  );
};

export default BrowseSection;
```

Note that both `id` and `instanceId` should match.
