### ISSUE TITLE
regeneratorRuntime is not defined - NextJS Build Error

### ISSUE THREAD

**Issue by tomthornton** [Tintef/react-google-places-autocomplete#97]
Works fine in production, but is throwing an error in my builds.

`> Build error occurred
ReferenceError: regeneratorRuntime is not defined
    at /tmp/build_36f04826_/node_modules/react-google-places-autocomplete/dist/react-google-places-autocomplete.cjs.prod.js:317:48
    at /tmp/build_36f04826_/node_modules/react-google-places-autocomplete/dist/react-google-places-autocomplete.cjs.prod.js:346:4
    at Object.<anonymous> (/tmp/build_36f04826_/node_modules/react-google-places-autocomplete/dist/react-google-places-autocomplete.cjs.prod.js:382:2)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/build_36f04826_/node_modules/react-google-places-autocomplete/dist/react-google-places-autocomplete.cjs.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)`

**Comment by Tintef** [comment]
@tomthornton My guess is that you need to add the babel config to support async/await.

If you can share a minimal reproducible repository, I can take a deeper look.

**Comment by macrozone** [comment]
@tomthornton we have also the same problem with nextjs in a project. It works fine in develop, but once you try to build you will get this error

**Comment by alessandrocalia** [comment]
We have the same problem with Gatsby. It works fine in develop, but once you try to build you will get this error

**Comment by alessandrocalia** [comment]
We have the same problem with Gatsby. It works fine in develop, but once you try to build you will get this error

**Comment by zollinger** [comment]
@Tintef here's a minimal next.js project for you to reproduce the issue (run the dev server or build):
https://github.com/zollinger/repro-react-google-places-autocomplete-nextjs

**Comment by Tintef** [comment]
Thanks! I'll try to take a look today or tomorrow at this.

I remember [this issue](https://github.com/Tintef/react-google-places-autocomplete/issues/34) about styles on next.js, could that be the issue?

Please let me know if any of you guys have the chance to try that (or know that that's not the issue 😅 ).

**Comment by Tintef** [comment]
@zollinger @macrozone @tomthornton Can any of you guys test the `2.3.0-beta.1` version?

```yarn add react-google-places-autocomplete@2.3.0-beta.1```

It's working for me in @zollinger repro repo, but I would like someone else to give it a try before releasing it. Thanks!

**Comment by Tintef** [comment]
Fix released on v2.3.0

If it doesn't work, please comment here or open a new issue
